### ISSUE TITLE
Cannot call seek(IO::Handle: Int, Int); none of these signatures match

### ISSUE THREAD

**Issue by pjscott** [labster/perl6-File-Compare#4]
==> Fetching File::Compare
==> Building File::Compare
==> Testing File::Compare
t/00-basic.t ..... ok
Cannot call seek(IO::Handle: Int, Int); none of these signatures match:
    (IO::Handle:D $: Int:D $offset, SeekType:D $whence = { ... }, *%_)
  in sub compare_multiple_files at /Users/peter/.panda-work/1450491380_1/lib/File/Compare.pm6:64
  in block <unit> at t/01-multiple.t:18

t/01-multiple.t .. 
Dubious, test returned 255 (wstat 65280, 0xff00)
Failed 7/7 subtests 
## Test Summary Report

t/01-multiple.t (Wstat: 65280 Tests: 0 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 7 tests but ran 0.
Files=2, Tests=8,  7 wallclock secs ( 0.03 usr  0.01 sys +  5.78 cusr  0.45 csys =  6.27 CPU)
Result: FAIL
test stage failed for File::Compare: Tests failed
  in method install at /Users/peter/.rakudobrew/moar-nom/install/share/perl6/site/sources/78C9B51F9F17D6ED0172444363DFABED219AB028:142
  in method resolve at /Users/peter/.rakudobrew/moar-nom/install/share/perl6/site/sources/78C9B51F9F17D6ED0172444363DFABED219AB028:219
  in sub MAIN at /Users/peter/.rakudobrew/moar-nom/install/share/perl6/site/resources/C9132EF472C961D01FA21E7E1A6A104EF2F6779D:18
  in block <unit> at /Users/peter/.rakudobrew/moar-nom/install/share/perl6/site/resources/C9132EF472C961D01FA21E7E1A6A104EF2F6779D:150
## Failure Summary

File::Compare(
        *test stage failed for File::Compare: Tests failed)

This is Rakudo version 2015.11-669-g1f09c1e built on MoarVM version 2015.11-106-g7545aa9
implementing Perl 6.b.

**Comment by labster** [comment]
Thanks for the report.  v6.b seems to be breaking all of my modules.
